#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pypi-matplotlib_inline
Version  : 0.1.6
Release  : 19
URL      : https://files.pythonhosted.org/packages/d9/50/3af8c0362f26108e54d58c7f38784a3bdae6b9a450bab48ee8482d737f44/matplotlib-inline-0.1.6.tar.gz
Source0  : https://files.pythonhosted.org/packages/d9/50/3af8c0362f26108e54d58c7f38784a3bdae6b9a450bab48ee8482d737f44/matplotlib-inline-0.1.6.tar.gz
Summary  : Inline Matplotlib backend for Jupyter
Group    : Development/Tools
License  : BSD-3-Clause
Requires: pypi-matplotlib_inline-license = %{version}-%{release}
Requires: pypi-matplotlib_inline-python = %{version}-%{release}
Requires: pypi-matplotlib_inline-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : pypi(traitlets)
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
# Matplotlib Inline Back-end for IPython and Jupyter
This package provides support for matplotlib to display figures directly inline in the Jupyter notebook and related clients, as shown below.

%package license
Summary: license components for the pypi-matplotlib_inline package.
Group: Default

%description license
license components for the pypi-matplotlib_inline package.


%package python
Summary: python components for the pypi-matplotlib_inline package.
Group: Default
Requires: pypi-matplotlib_inline-python3 = %{version}-%{release}

%description python
python components for the pypi-matplotlib_inline package.


%package python3
Summary: python3 components for the pypi-matplotlib_inline package.
Group: Default
Requires: python3-core
Provides: pypi(matplotlib_inline)
Requires: pypi(matplotlib)
Requires: pypi(traitlets)

%description python3
python3 components for the pypi-matplotlib_inline package.


%prep
%setup -q -n matplotlib-inline-0.1.6
cd %{_builddir}/matplotlib-inline-0.1.6
pushd ..
cp -a matplotlib-inline-0.1.6 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1672289231
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz "
export FCFLAGS="$FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz "
export FFLAGS="$FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz "
export CXXFLAGS="$CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
python3 setup.py build

popd
%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pypi-matplotlib_inline
cp %{_builddir}/matplotlib-inline-%{version}/LICENSE %{buildroot}/usr/share/package-licenses/pypi-matplotlib_inline/d073b7e3714725726cdecb070a7a64f4ab1410bc || :
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----
pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
python3 -tt setup.py build install --root=%{buildroot}-v3
popd
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pypi-matplotlib_inline/d073b7e3714725726cdecb070a7a64f4ab1410bc

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
